#!/usr/bin/env python3
"""
Auto-generated by crypto-scan task — 2026-03-10
Run this script to store crypto scan results into the database.
Usage: cd /path/to/Trader && python3 run_crypto_scan.py
"""
import sys, os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, 'Social_Arb')

from services.shared.camillo_ideas import (
    get_ideas, init_ideas_db, store_idea, CamilloIdea, log_scan
)

init_ideas_db()

# ── Check existing ──
existing = get_ideas(instrument_type='crypto', limit=50)
existing_tickers = {i['ticker'] for i in existing}
print(f"Existing crypto ideas: {len(existing)}")
for i in existing:
    print(f"  {i['ticker']}: {i['camillo_grade']} ({i['camillo_score']}) - {i['stage']}")

ideas_created = 0

# ─────────────────────────────────────────────────────────────────────────────
# SIGNAL 1: io.net (IO) — DePIN GPU Compute, Solana-based
# Score: ~60.5 → Grade B
# ─────────────────────────────────────────────────────────────────────────────
if 'IO' not in existing_tickers:
    idea = CamilloIdea(
        instrument_type='crypto',
        ticker='IO',
        name='io.net',
        stage='signal',
        signal_source='web',
        signal_description=(
            'io.net has connected 100,000+ GPUs as of 2025, creating a decentralized '
            'compute marketplace built on Solana. GPU supply is constrained globally — '
            'Nvidia confirmed demand exceeds supply into fiscal 2026. io.net offers '
            'cost-efficient GPU access for AI/ML workloads, paying contributors $IO tokens. '
            'Santiment shows Solana ecosystem developer activity surging, and daily active '
            'addresses hit 3.78M in early 2026 (+72% YoY).'
        ),
        signal_date='2026-03-10',
        thesis=(
            'The Camillo connection: AI developers and ML engineers are frustrated by '
            'GPU wait times and cloud costs (AWS/GCP). They are discovering io.net through '
            'builder Discords and AI hacker communities — NOT through CT. This is exactly '
            'the non-financial signal Camillo looks for. GPU demand is structural, not '
            'cyclical. As AI usage scales, so does demand for $IO. The token is utility-tied '
            'to actual compute usage — not speculation. Narrative is DePIN×AI, still pre-CT-consensus.'
        ),
        narrative='DePIN × AI Compute',
        c1_organic=0.65,    # Builders/devs using it, not CT influencers
        c2_velocity=0.65,   # 100K+ GPUs, rapid growth curve
        c3_crossplatform=0.55,  # AI community + Solana DeFi + DePIN builders
        c4_premainstream=0.60,  # Below most analyst radar
        c5_pricetotrend=0.65,   # AI compute demand structural, token may lag
        c6_category=0.50,       # Infrastructure, but directly enabling AI
        c7_demographic=0.55,    # AI engineers entering crypto via this
        c8_timing=0.65,         # GPU shortage + AI demand window open
        confidence=0.72,
    )
    id1 = store_idea(idea)
    print(f"Stored #{id1}: IO - score={idea.camillo_score}, grade={idea.camillo_grade}")
    ideas_created += 1
else:
    print("IO already exists, skipping")

# ─────────────────────────────────────────────────────────────────────────────
# SIGNAL 2: Geodnet (GEOD) — DePIN Geospatial, 518% YoY revenue
# Score: ~65.1 → Grade B (near A threshold)
# ─────────────────────────────────────────────────────────────────────────────
if 'GEOD' not in existing_tickers:
    idea = CamilloIdea(
        instrument_type='crypto',
        ticker='GEOD',
        name='Geodnet',
        stage='signal',
        signal_source='web',
        signal_description=(
            'Geodnet is a DePIN geospatial network that grew to $3M annualized network '
            'fee revenue in January 2025, representing ~518% year-over-year growth. '
            'The network provides high-precision GPS correction data (RTK) used by '
            'autonomous vehicles, drones, precision agriculture, and construction. '
            'Revenue comes from enterprise customers paying for actual data — this is '
            'real fee revenue, not token speculation. The project is virtually absent '
            'from mainstream crypto media.'
        ),
        signal_date='2026-03-10',
        thesis=(
            'The Camillo connection: precision GPS data is a $2B+ industry dominated by '
            'Trimble and Hexagon. Geodnet is disrupting it with decentralized infrastructure. '
            'The 518% revenue growth is not being discussed on CT. Enterprise mapping, '
            'autonomous vehicle testing, and drone regulations are driving real demand '
            'visible in trade publications and engineering communities — not financial media. '
            'This is a Camillo-classic "real-world signal before the market prices it" setup. '
            'Small cap + real revenue + zero analyst coverage = max information gap.'
        ),
        narrative='DePIN Real-World Data',
        c1_organic=0.75,    # Real fee revenue from enterprise customers
        c2_velocity=0.75,   # 518% YoY growth — exceptional
        c3_crossplatform=0.45,  # Engineering/mapping communities, not broad crypto
        c4_premainstream=0.80,  # Virtually zero mainstream crypto coverage
        c5_pricetotrend=0.70,   # Small cap with real revenue growth
        c6_category=0.45,       # Infrastructure, enterprise-facing
        c7_demographic=0.50,    # Enterprise mapping/AV/drone sector
        c8_timing=0.65,         # Early in discovery phase
        confidence=0.76,
    )
    id2 = store_idea(idea)
    print(f"Stored #{id2}: GEOD - score={idea.camillo_score}, grade={idea.camillo_grade}")
    ideas_created += 1
else:
    print("GEOD already exists, skipping")

# ─────────────────────────────────────────────────────────────────────────────
# SIGNAL 3: Bittensor (TAO) — AI subnet marketplace, post-halving
# Score: ~57.1 → Grade B
# ─────────────────────────────────────────────────────────────────────────────
if 'TAO' not in existing_tickers:
    idea = CamilloIdea(
        instrument_type='crypto',
        ticker='TAO',
        name='Bittensor',
        stage='signal',
        signal_source='web',
        signal_description=(
            'Bittensor now has 128 active subnets — specialized ML model competitions '
            'where validators stake TAO to back the best models. In December 2025 the '
            'network executed a halving event, reducing daily TAO emissions from 7,200 '
            'to 3,600. Santiment data shows meaningful developer activity. The Cortex '
            'subnet (text-to-image) and PromptIQ (LLM routing) subnets are gaining '
            'organic traction among AI researchers who prefer decentralized inference '
            'over OpenAI API lock-in.'
        ),
        signal_date='2026-03-10',
        thesis=(
            'The Camillo connection: AI researchers are ideologically motivated to '
            'use decentralized AI infrastructure. They are discovering TAO subnets through '
            'arXiv, HuggingFace communities, and AI Discord servers — not from CT. '
            'Post-halving supply reduction + growing subnet demand = supply shock. '
            'The signal: AI researchers talking about Bittensor in non-financial forums '
            '(academic Twitter, ML Discords) before it reaches mainstream CT consensus. '
            'This is the pre-mainstream window Camillo looks for.'
        ),
        narrative='AI × Crypto Infrastructure',
        c1_organic=0.65,    # AI researchers/builders, non-financial sources
        c2_velocity=0.55,   # Growing but somewhat known to CT already
        c3_crossplatform=0.60,  # AI Twitter + crypto builders + arXiv
        c4_premainstream=0.45,  # More CT-known than others
        c5_pricetotrend=0.55,   # Post-halving supply shock potential
        c6_category=0.55,       # AI infrastructure, critical layer
        c7_demographic=0.65,    # AI researchers genuinely entering crypto
        c8_timing=0.60,         # Post-halving window, still early
        confidence=0.65,
    )
    id3 = store_idea(idea)
    print(f"Stored #{id3}: TAO - score={idea.camillo_score}, grade={idea.camillo_grade}")
    ideas_created += 1
else:
    print("TAO already exists, skipping")

# ─────────────────────────────────────────────────────────────────────────────
# SIGNAL 4: Ondo Finance (ONDO) — RWA tokenized Treasuries, institutional
# Score: ~58.3 → Grade B
# ─────────────────────────────────────────────────────────────────────────────
if 'ONDO' not in existing_tickers:
    idea = CamilloIdea(
        instrument_type='crypto',
        ticker='ONDO',
        name='Ondo Finance',
        stage='signal',
        signal_source='web',
        signal_description=(
            'On-chain US Treasuries reached $8.7B (45% of total $19.4B RWA TVL). '
            'BlackRock BUIDL fund crossed $1B on-chain. Ondo Finance is the leading '
            'protocol for tokenized Treasuries accessible to retail. McKinsey forecasts '
            'RWA tokenization at $2T by 2030; current market is $19.4B — less than 1% '
            'penetrated. Franklin Templeton, JPMorgan, and BlackRock have all launched '
            'tokenized fund products in 2025-2026. Ondo sits at the retail-accessible '
            'layer that institutions are not directly competing in.'
        ),
        signal_date='2026-03-10',
        thesis=(
            'The Camillo connection: Traditional finance professionals are searching for '
            'on-chain yield products — this behavior is visible in fintech/TradFi LinkedIn '
            'groups, wealth management forums, and fintech newsletters (NOT crypto media). '
            'The institutional validation (BlackRock, Franklin Templeton) is the non-financial '
            'signal that the narrative is legitimate. Ondo is the retail bridge. '
            'New demographic entering: TradFi professionals who understand T-bill yields '
            'but are new to DeFi. The narrative is still pre-mainstream crypto consensus — '
            'most CT still discusses RWA as "next cycle" not current.'
        ),
        narrative='RWA Tokenization',
        c1_organic=0.45,    # Institutional + fintech community — somewhat less organic
        c2_velocity=0.65,   # RWA sector growing fast, institutional inflows
        c3_crossplatform=0.65,  # TradFi + crypto + fintech communities
        c4_premainstream=0.45,  # Covered in crypto media, but underpriced vs. scale
        c5_pricetotrend=0.60,   # <1% penetrated vs. $2T target
        c6_category=0.55,       # Financial products — strong consumer demand pull
        c7_demographic=0.70,    # TradFi institutions/professionals entering for real
        c8_timing=0.65,         # Regulatory clarity + adoption wave now
        confidence=0.68,
    )
    id4 = store_idea(idea)
    print(f"Stored #{id4}: ONDO - score={idea.camillo_score}, grade={idea.camillo_grade}")
    ideas_created += 1
else:
    print("ONDO already exists, skipping")

# ── Log the scan ──
log_scan(
    'crypto-scan', 'crypto',
    searches=5,
    facts_found=12,
    ideas_created=ideas_created,
    ideas_updated=0,
    top_signal='GEOD — 518% YoY revenue growth, zero analyst coverage, $3M annualized fees',
    summary=f'Found {ideas_created} qualifying signals (B-grade): DePIN GPU (IO), DePIN Geospatial (GEOD), AI subnets (TAO), RWA tokenized Treasuries (ONDO)'
)
print(f"\nScan complete. {ideas_created} ideas stored.")
print("Scan logged successfully")
